### ISSUE TITLE
Version 4.0 missing on Bionic

### ISSUE THREAD

**Issue by rvaser** [egor-tensin/setup-clang#1]
Dear Egor,
I am unable to setup Clang 4.0 with the following snippet:
```yaml
name: Setup Clang
uses: egor-tensin/setup-clang@v1
with:
  version: 4.0
  platform: x64
```
I get the errror:
```bash
E: The repository 'http://apt.llvm.org/bionic llvm-toolchain-bionic-4 Release' does not have a Release file.
```
The version is missing from https://apt.llvm.org/bionic/dists/.

Best regards,
Robert

P.S. Full workflow is at https://github.com/rvaser/test/blob/master/.github/workflows/test.yml.
