### ISSUE TITLE
Cache support

### ISSUE THREAD

**Issue by BlurringShadow** [egor-tensin/setup-clang#2]
Is it possible to use cache action like the following code?
```
     - name: Restore artifacts.
        uses: actions/cache@v2
        with:
          path: |
            ${{ **LLVM PATH HERE** }}
          key: |
            ${{ env.LLVM_VER}}
```
